### ISSUE TITLE
SMTP Connection with GMAIL

### ISSUE THREAD

**Issue by aarav22** [tlsfuzzer/tlslite-ng#485]
I'm trying to simply connect with Gmail, but I keep getting a handshake failure. 
This is the code I'm using. I'm using the app password and not my account password for authentication (though it doesn't seem to be making a difference)

`s = SMTP_TLS("smtp.gmail.com", 587) `
`print(s.ehlo())`
`print(s.starttls(username= email, password= password))`

The error
...\tlslite\tlsrecordlayer.py", line 707, in _getMsg
    raise TLSRemoteAlert(alert)
tlslite.errors.TLSRemoteAlert: handshake_failure

Thanks!

P.S this is working perfectly with smtplib but there I'm also calling login()

**Comment by tomato42** [comment]
Then I can't reproduce it, I'm getting a proper handshake.

**Comment by tomato42** [comment]
I don't think you're running current master branch, line 707 can't throw an exception:
https://github.com/tlsfuzzer/tlslite-ng/blob/dabc18f44bdfde944549822c1e4365e2267cdec9/tlslite/tlsrecordlayer.py#L707

**Comment by aarav22** [comment]
Sorry, I was using pip. But built it just now from master and got the same error.
`lib\site-packages\tlslite\tlsrecordlayer.py", line 1080, in _getMsg
    raise TLSRemoteAlert(alert)
tlslite.errors.TLSRemoteAlert: handshake_failure`

**Comment by tomato42** [comment]
Like I said, can't reproduce, `starttls()` doesn't abort for me. 

The error means that the server rejected our ClientHello message: the algorithms tlslite-ng advertised as supported for the connection. It may be possible to fix it by changing what tlslite-ng advertises.

**Comment by aarav22** [comment]
Sorry just to confirm, are you reproducing this with Gmail or a different server? 

> It may be possible to fix it by changing what tlslite-ng advertises

Could you refer to some resources?

**Comment by aarav22** [comment]
Yep, truly can't find what's going wrong. There is not even a detailed message as to why the handshake is going wrong. I just receive a header of type Alert, and the code just leads to a "handshake failure" msg.

**Comment by tomato42** [comment]
> Sorry, just to confirm are you reproducing this with Gmail or a different server?

yes, with gmail

> Could you refer to some resources?

It's controlled through the [HandshakeSettings](https://tlslite-ng.readthedocs.io/en/latest/tlslite.handshakesettings.html) object

> I tested on mailtrap, same handshake failure error.

maybe the problem is some middlebox, not the server config?

> There is not even a detailed message as to why the handshake is going wrong.

That's because there is no detailed message, the TLS specifies just few generic error IDs and everything is reduced down to them, so the only information that tlslite-ng gets from the server is "error number 40", which it then translates to "handshake_failure". The only way to diagnose it further is to experiment on the server and guess what's the issue.

**Comment by aarav22** [comment]
Hmm, tested in multiple virtual envs, different networks and even a different device but still the same failure. I'm just curious because this works with smtplib. If I just call the login() from smtplib rather than SRP login through STARTLS, it works.

**Comment by aarav22** [comment]
I think I have something now. Can you guide me on how to extend the ciphersuites?
![image](https://user-images.githubusercontent.com/40788319/201020151-b5b77251-f7f7-411d-8236-51b0eba16db3.png)

**Comment by tomato42** [comment]
It's the `cipherNames` in HandshakeSettings, but by default all reasonable ones are enabled, so that looks like a red herring to me.

Do packet capture of working and non-working connection, paste the decoded working and non-working clienthello here.

**Comment by aarav22** [comment]
Okay, so I think I have something. This image is for ClientHello when I pass the credentials in starttls(username=.., password=...)
![image](https://user-images.githubusercontent.com/40788319/201726465-2ba068a3-68ba-4064-92d7-696f3dd5ee3d.png)

This one is when I don't, which seems more like the standard. 
![image](https://user-images.githubusercontent.com/40788319/201726851-a42b1e36-9dfa-4d54-8254-9afe524f7887.png)

**Comment by tomato42** [comment]
aah, that's because the `.starttls()` `password=` and `username=` is not SMTP password and username but [SRP password and username](https://tlslite-ng.readthedocs.io/en/latest/tlslite.integration.smtp_tls.html?highlight=starttls#tlslite.integration.smtp_tls.SMTP_TLS.starttls). Don't specify them there and it will work fine.
You should use the [`login()` method](https://docs.python.org/3/library/smtplib.html#smtplib.SMTP.login) to provide the SMTP user name an login.

**Comment by aarav22** [comment]
Yep, that's ...it. Thank you!
